### ISSUE TITLE
How to build and run on GNU/Linux?

### ISSUE THREAD

**Issue by nnn1590** [Gericom/EveryFileExplorer#38]
**_This sentence was translated by google translation._**

I tried:
- Mono
- .NET Core 2.2

But I couldn't build.
<hr>
Replace "&lt;TargetFrameworkVersion&gt;v4.0&lt;/TargetFrameworkVersion&gt;"<br>
with "&lt;TargetFramework&gt;netcoreapp2.2&lt;/TargetFramework&gt;",<br>
and delete &lt;PostBuildEvent&gt; and execute xbuild, I could build except NDS.<br>
(NDS fails with "CS0246: The type or namespace name 'Tao' could not be found".)<br>
But that exe does not start in Mono<br>
(exe location = "EveryFileExplorer.git/EveryFileExplorer/bin/Debug/EveryFileExplorer.exe")<br>
In Wine (x86-PREFIX + winetricks net461), although the main window is displayed, nothing works.<br><hr>
"&lt;TargetFrameworkVersion&gt;v4.0\&lt;/TargetFrameworkVersion&gt;"<br>
を"&lt;TargetFramework&gt;netcoreapp2.2&lt;/TargetFramework&gt;"に置換してから、<br>
&lt;PostBuildEvent&gt;を削除してxbuildを実行するとNDS以外はビルドできました。<br>
(NDSは"CS0246: The type or namespace name 'Tao' could not be found"で失敗します。)<br>
しかしそのexeはMonoでは起動せず、<br>
(exeの場所 = "EveryFileExplorer.git/EveryFileExplorer/bin/Debug/EveryFileExplorer.exe")<br>
Wine(x86-PREFIX + winetricks net461)ではメインウィンドウが表示されるものの何も動きません。

**Comment by CuriousTommy** [comment]
Honestly, this project seems to be dead. If you only need to extract the game model files, consider using [SPICA](https://github.com/gdkchan/SPICA) instead.

**Comment by nnn1590** [comment]
Thank you very much!
