### ISSUE TITLE
Thnking on upload a release?

### ISSUE THREAD

**Issue by ElHave247** [Gericom/EveryFileExplorer#46]
Why you force all peple to build? you understand there is noob dont know build things, and install visual studio and required dependencies can be a pain for him?, or just dont have the power of pc to make all the process, Put a release build dont have any cost!

**Comment by Masamune3210** [comment]
1. The last commit was in 2015. It's pretty safe to say that its dead. 
2. Building the program is not hard.
3. Please don't go around demanding people to do things. It's usually not going to end well.

**Comment by ElHave247** [comment]
Lol you are demanding people do things, is nice then. Be unfair with users.

**Comment by Masamune3210** [comment]
I....didn't demand anything.....

**Comment by ElHave247** [comment]
2.Building the program is not hard. This is for you, you can understand there is people with no experience doing it?
